### ISSUE TITLE
Some missing countries

### ISSUE THREAD

**Issue by alexrutherford** [leoferres/cdrcountries#1]
Turkey had a whole conference dedicated to it in 2018! [Data4Refugees](https://d4r.turktelekom.com.tr) 

[Bangladesh](https://link.springer.com/article/10.1007/s10584-016-1753-7)

[Pakistan](https://www.pnas.org/content/112/38/11887.long)

[England](http://www.uvm.edu/pdodds/files/papers/others/everything/beep2010a.pdf)

**Comment by leoferres** [comment]
Done! Thank you, @alexrutherford!
